### PR TITLE
added sound

### PR DESCRIPTION
**Pull request by markussite**

### CODE REVIEW

**Comment by mango1603** [comment]
image

I found bug here when it the music button is displayed as Sound

**Comment by mango1603** [comment]
image
Also, in the play scene, can you separate the music button and sound button? It would be cool

**Review by NadyaKan — COMMENTED** [review]
sound on click is working, and the toggle bug on the SettingsScene is fixed

**Review by Deumlich-S0573093 — DISMISSED** [review]
Music and sound buttons in the GamePlay scene work as it should.
Music and sound buttons in the Settings scene work as it should.
(there is no sound playing when clicking on a node yet)

**Review by NadyaKan — COMMENTED** [review]
oh sorry , just realised that the icons were interchanged. everything is working fine, except of the missing sound when clicking on the node.

**Comment by mango1603** [comment]
Can you create a new asset directory to store sound/music as we agreed?

**Comment by markussite** [comment]
> Can you create a new asset directory to store sound/music as we agreed?

I thought mohammad is doing the refactoring of the assets but sure I can do that.

**Pull request closed without merging**
